### ISSUE TITLE
INFOGRAFIA GESTION DE PROYECTOS

### ISSUE THREAD

**Issue by EDITH-R** [SistemasTecTlaxiaco/infografia-EDITH-R-1#2]
![INFOGRAFIA](https://user-images.githubusercontent.com/72045371/132249895-2c809475-d162-4f39-b5ff-339592a1ded6.png)

**Comment by IvanMc98** [comment]
La infografía cuenta con todos los puntos que marca la rubrica.
Calificación : 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
